export const NEW_PRODUCT_CATEGORY = "NEW_PRODUCT_CATEGORY";
export const ALL_PRODUCT_CATEGORY = "ALL_PRODUCT_CATEGORY";
export const PRODUCT_CATEGORY_BY_ID = "PRODUCT_CATEGORY_BY_ID";
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";
export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";
export const UPLOAD_PRODUCT_CATEGORY_IMG = "UPLOAD_PRODUCT_CATEGORY_IMG";
